### ISSUE TITLE
Remover a unicidade do campo "Nome" no formulario de cadastro.

### ISSUE THREAD

**Issue by brunocfreitas** [tasafo/palestras-coletivas#27]
Ao fazer cadastro no site ele pede primeiro e ultimo nome e tiver problemas porque ja tinha outro Bruno Freitas cadastrado, deve ter varios Bruno Freitas, Maria Silva, etc... Acredito que apenas o username deve ser unico.

**Comment by pigor** [comment]
Muito bom @brunocfreitas, obrigado pela contribuição!

**Comment by luizsanches** [comment]
@brunocfreitas, foi removida a unicidade. Também foi revisada a tela de cadastro de usuário para deixá-la mais informativa. Valeu!

**Comment by pigor** [comment]
@brunocfreitas você pode conferir a correção no commit 7e952f2, segue o link - https://github.com/tasafo/palestras-coletivas/commit/7e952f2d577e240942eb92c5d2d6b74e2f1af81c#diff-4676c008b11a5480d73d4a6de01e45b9L37 - nesse mesmo commit tem várias outras alterações, a que tirou o problema que você relatou está na linha 37 do arquivo app/models/user.rb

**Comment by brunocfreitas** [comment]
Muito bom, valeu galera pelo retorno.
