### ISSUE TITLE
Despublicar eventos

### ISSUE THREAD

**Issue by mfandrade** [tasafo/palestras-coletivas#32]
Uma vez que tenha sido criado e publicado um evento que eventualmente tenha de ser cancelado, não está sendo possível removê-lo/despublicá-lo do Palestras Coletivas.

**Comment by luizsanches** [comment]
A operação de despublicar o evento está funcionando retirando o mesmo da lista de eventos. Só não estava retirando ele dos slides da homepage. Agora foi corrigido.

Valeu, @mfandrade!
