### ISSUE TITLE
Adicionar link para o repositório no front end

### ISSUE THREAD

**Issue by lubien** [tasafo/palestras-coletivas#33]
Chama atenção para contribuidores OS.

**Comment by ffmarcos** [comment]
Na verdade é melhorar o link, ele tá como "Fonte" no menu superior, talvez colocar um ícone do github, ou mover ele pro final que é um lugar mais "comum".

**Comment by lubien** [comment]
Engraçado, eu devo ter visto e ignorado completamente kk.
Usar o icone chama mais atenção msm!

**Comment by ffmarcos** [comment]
Exatamente, só fui achar pq eu ia criar uma issue exatamente como essa e acabei procurando pra ver se realmente tinha haha

**Comment by lubien** [comment]
Apesar de ter resolvido a Issue, vo deixa aqui pra ver se algum contribuidor acha válido usar a logo do github

**Comment by luizsanches** [comment]
@ffmarcos e @lubien, valeu pela força. Já está no ar! Aguardamos novas contribuições :)
